export const commands = [
  {
    id: "dashboard",
    type: "page",
    title: "Dashboard",
    subtitle: "View your financial dashboard",
    icon: "🏠",
    path: "/",
  },
  {
    id: "bills",
    type: "page",
    title: "Bills",
    subtitle: "Manage your bills",
    icon: "💳",
    path: "/bills",
  },
  {
    id: "budget",
    type: "page",
    title: "Budget",
    subtitle: "View your monthly budget",
    icon: "💰",
    path: "/budget",
  },
  {
    id: "calendar",
    type: "page",
    title: "Calendar",
    subtitle: "Review due dates and bill reminders",
    icon: "📅",
    path: "/calendar",
  },
  {
    id: "savings",
    type: "page",
    title: "Savings",
    subtitle: "Savings goals and progress",
    icon: "🏦",
    path: "/savings",
  },
  {
    id: "debt",
    type: "page",
    subtitle: "Track debt payoff",
    title: "Debt",
    icon: "💳",
    path: "/debt",
  },
  {
    id: "reports",
    type: "page",
    title: "Reports",
    subtitle: "View financial reports",
    icon: "📊",
    path: "/reports",
  },
  {
    id: "settings",
    type: "page",
    title: "Settings",
    subtitle: "Customize BudgetForge",
    icon: "⚙️",
    path: "/settings",
  },
];
