export function toIncomeRow(entry, userId) {
  return {
    id: entry.id,
    user_id: userId,
    entry_mode: entry.entryMode,
    source_type: entry.sourceType,
    source_name: entry.sourceName,
    amount: entry.amount,
    date_received: entry.dateReceived,
    deposit_method: entry.depositMethod,
    notes: entry.notes || "",
    employer: entry.employer || null,
    pay_period_start: entry.payPeriodStart || null,
    pay_period_end: entry.payPeriodEnd || null,
    hourly_rate: entry.hourlyRate ?? null,
    regular_hours: entry.regularHours ?? null,
    overtime_hours: entry.overtimeHours ?? null,
    overtime_multiplier: entry.overtimeMultiplier ?? null,
    gross_pay: entry.grossPay ?? null,
    federal_tax: entry.federalTax ?? null,
    state_tax: entry.stateTax ?? null,
    local_tax: entry.localTax ?? null,
    social_security_tax: entry.socialSecurityTax ?? null,
    medicare_tax: entry.medicareTax ?? null,
    health_insurance: entry.healthInsurance ?? null,
    retirement_contribution: entry.retirementContribution ?? null,
    other_deductions: entry.otherDeductions ?? null,
    total_deductions: entry.totalDeductions ?? null,
    net_pay: entry.netPay ?? null,
    created_at: entry.createdAt,
    updated_at: entry.updatedAt,
  };
}
